### ISSUE TITLE
MVP Roadmap

### ISSUE THREAD

**Issue by nmoroze** [nmoroze/tclint#2]
**Parser**

- [x] Add expressions 
- [x] Proper syntax errors
- [x] Recursive parse for all commands
- [x] Node objects all the way down

**Frontend**

- [x] Ability to run recursively on directory
- [x] Exclude option
- [x] Option to select command plugins
- [x] Config file mirroring CLI options (.toml)
  - [x] Fileset

**Checker**

- [x] Check formatting
- [x] ~Check commands defined (with plugin system)~ WONTFIX: can't disambiguate between calling builtin commands and procs, and we can't get a set of all procs defined without implementing `source` following. Alternative: ensure builtin names aren't overwritten 
- [x] Ability to disable checks w/ config or comment
- [x] Output w/ ~numbered errors~ IDs

**Polish**

- [x] black formatting
- [x] CI
- [ ] Type annotations w/ checking. Probably a WONTFIX on annotating entire repo, but would be nice to try and get some sort of useful checking going w/ existing annotations and mypy added to CI. 
- [x] linting
- [x] README
- [x] packaging + publish to pypi
